/* ============================================================
   Elden Rogue – Internationalization (i18n) Module
   ============================================================ */
(function () {
  "use strict";

  const TRANSLATIONS = {
    de: {
      // General UI
      author_tag: "by Hoschi",
      mode_normal: "Normaler Modus",
      mode_hard: "Schwerer Modus (In Entwicklung)",
      tab_game: "Spiel",
      tab_leaderboard: "Bestenliste",
      tab_achievements: "Achievements",
      
      // Account Bar
      loading: "Lade…",
      unregistered: "Nicht angemeldet",
      unregistered_sub: "Melde dich an, um Fortschritt & Bestenliste online zu speichern",
      registered_sub: "Angemeldet · Fortschritt wird online gespeichert",
      local_mode: "Lokaler Modus",
      local_mode_sub: "Online-Login & Online-Bestenliste sind noch nicht eingerichtet (siehe FIREBASE_SETUP.md)",
      btn_login: "Mit Google anmelden",
      btn_logout: "Abmelden",
      btn_save: "Speichern",
      lbl_name: "Name:",
      saved_alert: "Name gespeichert: ",

      // Rules
      rules_title: "Die Gesetze der Zwischenlande",
      rule_1: "<strong>Pfadwahl:</strong> Euer Weg führt über verzweigte Knotenpunkte. Wählt weise, um tiefer vorzudringen.",
      rule_2: "<strong>Waffen & Upgrades:</strong> Findet neue Waffen und verbessert sie; Upgrades werden beim Waffenwechsel übertragen.",
      rule_3: "<strong>Die Blaidd-Quest:</strong> Bezwingt Blaidd 4 Mal, um seine Questlinie und einen mächtigen Bonus freizuschalten.",
      rule_4: "<strong>Segen der Gnade:</strong> Rasten und Bossbesiege stellen Leben und Flakons voll wieder her.",
      rule_5: "<strong>Große Runen:</strong> Bezwingt die Halbgötter, um Runen an den Heiligen Türmen zu aktivieren.",

      // Leaderboard
      lb_loading: "Lade Bestenliste…",
      lb_no_entries_online: "Noch keine Einträge – sei der Erste!",
      lb_no_entries_local: "Noch keine lokalen Läufe. Spiel eine Runde, um in die Bestenliste zu kommen!",
      lb_local_hint: "(Lokale Bestenliste – für eine geräteübergreifende Online-Liste Firebase einrichten.)",
      lb_th_player: "Befleckter",
      lb_th_stage: "Etappe",
      lb_th_bosses: "Bosse",
      lb_th_score: "Score",

      // Map Nodes
      node_1: "Elite-Feind: Mehr Leben!",
      node_2: "Ruinen-Wächter: Waffenupgrade!",
      node_3: "Invader besiegen: Erhöht die Schmiedestufe!",
      node_4: "Ort der Gnade: Full Health",
      node_5: "Boss-Kampf! Der Weg ins nächste Gebiet!",
      node_6: "Schatztruhe öffnen: Zufälliger Talisman!",
      node_7: "Goldener Erdenbaum: +1 Flakon und +10% Estus-Effizienz",
      node_8: "Heiliger Turm: Rune aktivieren!",
      node_9: "NPC Quest: Triff auf Blaidd!",
      node_10: "Dungeon Katakomben: Betrete eine Mini-Etappe voller Loot!",
      node_11: "Skelett: Relativ schwach.",
      node_12: "Truhe plündern: 30% Chance für ein Buffitem!",
      node_13: "Durchgang durchschreiten: Pass auf die Fallen auf!",
      node_14: "Höhle: Rüstungsupgrade!",

      // Classes
      class_title: "Wähle deine Klasse, Befleckter...",
      class_vagabond: "Vagabund",
      class_vagabond_stats: "150 HP · 3 Flakons · 30% Rolle",
      class_vagabond_gear: "Großaxt · Vagabond Knight Set",
      class_samurai: "Samurai",
      class_samurai_stats: "110 HP · 2 Flakons · 40% Rolle",
      class_samurai_gear: "Uchigatana · Land of Reeds Set",
      class_wretch: "Bettler",
      class_wretch_stats: "90 HP · 1 Flakon · 50% Rolle",
      class_wretch_gear: "Keule · Keine Rüstung",

      // Sidebar & Stats
      backpack: "Inventar",
      backpack_empty: "Leer",
      backpack_buff: "Buff aktiv!",
      storage_title: "⚔️ Waffen-Lager",
      storage_empty: "Kein Lager-Waffe",
      storage_swap_tip: "Klicken, um diese Waffe auszurüsten (Tausch mit aktueller)",
      quest_ready: "Blaidd: Bereit für Belohnung!",
      talisman_slots: "Talismane",
      talisman_empty: "Leerer Talisman-Slot",
      talisman_locked: "Gesperrt – wird nach dem Sieg über Maliketh freigeschaltet",
      great_runes: "Große Runen",
      btn_new_run: "🔄 Neuen Run starten",
      btn_main_menu: "🏰 Hauptmenü",
      btn_twitch: "🎥 Twitch Kanal",
      btn_discord: "💬 Discord Server",
      current_area: "Aktuelles Gebiet",
      hp_display: "HP",
      dodge_roll: "Rolle",

      // Combat Arena
      combat_player: "DU",
      combat_enemy: "GEGNER",
      combat_staggered: "💥 GESTAGGERT!",
      btn_attack: "⚔️ Angreifen",
      btn_heal: "🧪 Heilen",
      tip_attack: "Führe einen Angriff mit deiner ausgerüsteten Waffe aus. Der Feind schlägt direkt im Anschluss zurück!",
      tip_heal: "Trinke einen Heilflakon, um schwere Wunden zu schließen. Achtung: Der Gegner darf dich währenddessen attackieren!",
      log_start: "Du forderst heraus: ",
      log_death: "💀 DU BIST GESTORBEN.",
      screen_death: "DU BIST GESTORBEN",

      // Dungeons & Shrines
      catacombs_title: "🏰 Katakomben entdeckt",
      catacombs_desc: "Du stehst vor den schweren Steintüren eines uralten Dungeons. Betrittst du ihn, wechselst du auf eine kleinere, gefährliche Nebenebene voller Loot, Monstern und einer Belohnung am Ende!",
      catacombs_btn: "Dungeon betreten ➔",
      chest_win: "🎁 Gegenstand geborgen!",
      chest_win_desc: "Du öffnest eine versteckte Steintruhe und verstaust das Item in deinem Rucksack:\n\n<strong>{item}</strong>\n({desc})",
      chest_win_btn: "Im Rucksack verstauen ➔",
      chest_full: "🎒 Rucksack voll!",
      chest_full_desc: "Du hättest eine <strong>{item}</strong> gefunden, aber dein Rucksack hat keine freien Slots mehr!",
      chest_full_btn: "Liegen lassen ➔",
      chest_empty: "📦 Leere Kiste",
      chest_empty_desc: "Die Truhe enthält nur Staub und wertlose Knochenreste. Nichts gefunden!",
      chest_empty_btn: "Weiter ➔",
      trap_win: "🏃 Sicherer Durchgang",
      trap_win_desc: "Geschickt schleichst du durch die Dunkelheit, meidest Guillotinen sowie Druckplatten und kommst ohne Kratzer auf der anderen Seite an!",
      trap_fail: "🏹 Falle ausgelöst!",
      trap_fail_desc: "Du übersiehst einen Stolperdraht! Giftpfeile schießen aus den Katakombenwänden.\n\nDu verlierst <span style='color:#e74c3c; font-weight:bold;'>{dmg} HP</span>.",
      trap_fail_btn: "Wunden flicken & weiter ➔",
      tower_title: "☤ Der Heilige Turm",
      tower_desc: "Wähle eine erbeutete Große Rune, um sie an diesem Altar exklusiv zu aktivieren.",
      tower_leave: "Turm verlassen ➔",
      tower_btn: "🏯 Battle Tower",
      tower_guide_title: "🗼 Battle Tower",
      tower_guide_sub: "20 Etagen. Ein Leben. Wie weit kommst du?",
      tower_guide_l1: "<b>20 Etagen</b>, jede eine kleine Mini-Karte mit Kämpfen und einem Boss am Ende – zufällig aus dem Boss-Pool und mit jeder Etage härter.",
      tower_guide_l2: "<b>Ein Leben:</b> Stirbst du, ist der Aufstieg vorbei – Neustart ab Etage 1. Deine HP tragen zwischen den Etagen mit.",
      tower_guide_l3: "<b>Nach jedem Boss</b> gewährt dir Melina einen dauerhaften Segen (Schaden, Max-HP, Flakon, Ausweichen …). Alle 5 Etagen aktivierst du zusätzlich eine <b>Große Rune</b>.",
      tower_guide_l4: "<b>Verhängnis-Etagen</b> (30 %): ein Fluch gilt für die <b>ganze Etage</b> – z.&nbsp;B. zähere Gegner, Scharlachfäule oder halbe Flakons. Wird oben angezeigt.",
      tower_guide_l5: "<b>Etage 20: Baby PCR</b> – bezwinge ihn und werde Meister des Turms.",
      tower_guide_l6: "Der Turm ist <b>brutal</b>: Du brauchst einen gut gelevelten Charakter (Roundtable) und etwas Glück. Deine Roundtable-Upgrades zählen voll.",
      tower_guide_start: "Turm betreten ⚔️",
      tower_guide_close: "Zurück",
      dex_title: "Eldendex",

      // Rewards & Boss Transitions
      grace_title: "✨ Segen der Gnade",
      grace_desc: "Du rastest am Ort der Gnade.\nDeine Lebenskraft und Flakons wurden vollständig regeneriert!",
      seed_title: "🌳 Goldene Saat gefunden",
      seed_desc: "Du stehst vor einem leuchtenden Erdenbaum-Sprössling.\n\nEffekt:\n🧪 +1 Flakon-Kapazität\n🧪 Estus heilt jetzt {pct}% deines max. Lebens!",
      loot_title: "Neue Waffe gefunden!",
      loot_desc: "Der Wächter ist gefallen und hinterlässt eine Waffe:",
      loot_dmg: "Basis-Schaden:",
      loot_type: "Schadensart:",
      loot_current: "(Aktuell ausgerüstet: {name} – Basis {dmg})",
      loot_hint: "Hinweis: Beim Ausrüsten wandert deine aktuelle Waffe ins Lager (falls Platz), sonst wird sie verworfen. Alle +Schmiedestufen gelten für jede Waffe im Run.",
      loot_btn_equip: "Ausrüsten",
      loot_btn_store: "Inventory",
      loot_btn_replace: "Ersetzen: {name}",
      loot_btn_trash: "❌ Wegwerfen",
      armor_title: "🛡️ Rüstung erbeutet!",
      armor_desc: "Der Mini-Boss ist gefallen und lässt eine Rüstung zurück:",
      armor_reduction: "Schadensreduktion:",
      armor_current: "Aktuell: {name}",
      armor_btn_equip: "🛡️ Anlegen",
      arcane_title: "⚔️ Arcane geskillt!",
      arcane_desc: "Du hast die Tiefen der Katakomben gesäubert.\nDeine Waffe zieht die Energie des Altars ein und besitzt nun die:",
      arcane_btn: "In die Zwischenlande zurückkehren ➔",
      quest_title: "🐺 Blaidds Vermächtnis",
      quest_desc: "Du hast den Halbwolf 4 Mal bezwungen. Wähle deine ultimative Belohnung (Quest resettet):",
      quest_opt_hp: "❤️ Rannis Umarmung",
      quest_opt_hp_sub: "Erhöht dein maximales Leben dauerhaft um +50%.",
      quest_opt_dmg: "⚔️ GÜLDIGES Upgrade",
      quest_opt_dmg_sub: "Deine aktuelle Waffe wird auf Legendär gehoben und erhält +40 Basis-Schaden.",
      quest_opt_roll: "💨 Wolfsreflexe",
      quest_opt_roll_sub: "Hebt deine Ausweich-Rolle auf 65% an (Hard Cap: 75%).",

      // Boss Defeat Text Blocks
      boss_godrick_win: "Godrick ist zerschmettert!\nDu erbeutest seine Große Rune.\n\nEin neuer Pfad öffnet sich: Das vom Scharlach verrottete Ödland... CAELID!",
      boss_radahn_win: "Du hast Radahn bezwungen!\nDas Schicksal setzt sich wieder in Bewegung.\n\nDein nächstes Ziel ist die goldene Hauptstadt... LEYNDELL!",
      boss_morgott_win: "Morgott löst sich in Goldstaub auf!\nDu erhältst Morgotts Große Rune (Verdoppelt dein maximales Leben).\n\nDer Weg führt dich nun hinauf in die eisigen, gefährlichen Höhen...\nMOUNTAINTOPS OF THE GIANTS!",
      boss_giant_win: "Der letzte Riese bricht im Schnee zusammen!\n\n🎒 Dein Waffen-Lager fasst ab jetzt 2 Waffen!\n\nEin Riss im Raum wirft dich in das zerfallende, zeitlose Himmelsreich...\nCRUMBLING FARUM AZULA!",
      boss_maliketh_win: "Maliketh ist gefallen. Die Rune des Todes ist entfesselt!\n\n💍 Du kannst ab jetzt einen 4. Talisman tragen!\n\nDie Hauptstadt brennt. Kehre zurück zur Aschehauptstadt!",
      boss_gideon_win: "Gideon wurde zum Schweigen gebracht.\n\nDer Weg zum Eldenthron ist frei. Mach dich bereit für den finalen Aufstieg!",
      boss_godfrey_win: "Godfrey hat dir Respekt gezollt und ist gefallen.\n\nDu spürst eine letzte rettende Gnade vor dir, bevor du das Innere des Erdenbaums betrittst...",
      boss_beast_win: "GOTT GESCHLACHTET.\n\nDu hast die Goldene Ordnung bezwungen und die Scherben vereint. Du bist der neue Elden Lord! GGG!",
      enemy_elite_win: "Der Wächter schwindet.\nDeine maximale Lebenskraft erhöht sich um +10% (+{hp} HP)!",
      enemy_skeleton_win: "Das Skelett zerbröselt zu wirrer Asche. Der Weg ist frei!",
      btn_continue: "Weiter ➔",

      // Items, Affinities, Armor Names
      item_dumpling: "Raw Meat Dumpling",
      item_dumpling_desc: "Erhöht das max. Leben um +15%.",
      item_neck: "Pickled Turtle Neck",
      item_neck_desc: "Erhöht Ausweichen flat um +15%.",
      item_flesh: "Exalted Flesh",
      item_flesh_desc: "Erhöht den Waffenschaden um +15%.",
      affinity_burst: "Burst",
      no_armor: "Keine Rüstung",
      armor_reduction_label: "−{pct}% Schaden",
      weapon_damage_label: "{dmg} Schaden",
      stagger_alert: "\n💥 Gegner gestaggert!! Er kann diese Runde nicht angreifen!",
      stagger_stuck: "\n💥 Der Gegner hängt im Stagger fest!",
      roll_success: "\n💨 Rollen-Erfolg! Du weichst dem Hieb komplett aus!",
      roll_fail: "\n{name} erwischt dich am Ende der Rolle für {dmg} Schaden!",
      heal_roll_success: "\n💨 Elegant rollst du dich während des Trinkens unter dem Schlag weg!",
      heal_roll_fail: "\n{name} bestraft das Heilen: {dmg} Schaden!",
      elden_beast_transition: "Radagon zerfällt zu Goldstaub...\n✨ DOCH AUS DER DUNKELHEIT ERHEBT SICH DAS ELDENBIEST! ✨",

      // Achievements Data
      // New Challenges
      challenge_noblaidd: "No Blaidd",
      challenge_noblaidd_desc: "Die Blaidd-Quest ist deaktiviert. Keine Begegnungen, keine Belohnungen.",
      challenge_noblaidd_skip_title: "🐺 Blaidd ignoriert",
      challenge_noblaidd_skip_desc: "Dein Ehrenkodex verbietet es dir, Blaidd zu begegnen. Du gehst weiter.",
      challenge_autobattle: "Auto-Battle",
      challenge_autobattle_desc: "Keine manuelle Kontrolle. Du greifst automatisch an, ohne Heilung.",
      no_armor: "Keine Rüstung",
      status_heading: "STATUS",

      // Seed-System & Ergebnis teilen
      seed_label: "Seed",
      seed_placeholder: "Seed eingeben…",
      seed_apply: "Übernehmen",
      seed_run_warn: "Seed-Run: Achievements, Fortschritt, Bestenlisten & Seelen sind deaktiviert.",
      seed_badge: "Seed-Run — zählt nicht",
      seed_copied: "Seed-Link kopiert!",
      share_result: "Ergebnis kopieren",
      share_copied: "✓ Kopiert!",
      share_fallen: "Gefallen in",
      share_victory: "ELDEN LORD",

      // Hard Mode & Challenge Achievements
      ach_complete_10_nm: "Veteran", ach_complete_10_ds: "Schließe 10 Runs ab.",
      ach_complete_25_nm: "Legende", ach_complete_25_ds: "Schließe 25 Runs ab.",
      ach_hard_5_nm: "Masochist", ach_hard_5_ds: "Schließe Hard-Mode 5x ab.",
      ach_malenia_nm: "Scarlet Bloom", ach_malenia_ds: "Besiege Malenia.",
      ach_rennala_nm: "Vollmondkönigin", ach_rennala_ds: "Besiege Rennala, Königin des Vollmonds.",
      ach_rykard_nm: "Gottverschlinger", ach_rykard_ds: "Besiege Rykard, Herrn der Blasphemie.",
      ach_unlock_gelmir_nm: "Der Weg des Vulkans", ach_unlock_gelmir_ds: "Folge einer geheimnisvollen Einladung.",
      ach_mohg_omen_nm: "Omen der Tiefe", ach_mohg_omen_ds: "Besiege Mohg, das Omen, in der Kanalisation.",
      ach_fall_death_nm: "Hätte eine Katze sein sollen", ach_fall_death_ds: "Stürze in der Kanalisation in den Abgrund.",
      ach_mohg_nm: "Miquellas Erwachen", ach_mohg_ds: "Besiege Mohg, Fürst des Blutes, und erwecke Miquella.",
      ach_unlock_mohgwyn_nm: "Ruf des Blutes", ach_unlock_mohgwyn_ds: "Lüfte ein weiteres Geheimnis des Zwischenlands.",
      ach_unlock_hard_nm: "Eine neue Prüfung", ach_unlock_hard_ds: "Schalte den Schweren Modus frei.",
      ach_unlock_malenia_nm: "Der verborgene Pfad", ach_unlock_malenia_ds: "Schalte den Pfad des Haligtree frei.",
      ach_unlock_tower_nm: "Tor zum Turm", ach_unlock_tower_ds: "Schalte den Battle Tower frei.",
      ach_unlock_liurnia_nm: "Ein verborgenes Geheimnis", ach_unlock_liurnia_ds: "Lüfte eines der Geheimnisse des Zwischenlands.",
      ach_loretta_nm: "Ritterin gefallen", ach_loretta_ds: "Besiege Loretta.",
      ach_niall_nm: "Kommandant besiegt", ach_niall_ds: "Besiege Commander Niall.",
      ach_death_100_nm: "Unsterblich", ach_death_100_ds: "Stirb 100 Mal.",
      ach_win_2500_nm: "Kriegsgott", ach_win_2500_ds: "Gewinne 2500 Kämpfe.",
      ach_all_bosses_nm: "Götterdämmerung", ach_all_bosses_ds: "Besiege jeden Halbgott mindestens einmal.",
      ach_hard_lord_nm: "Wahrer Elden Lord", ach_hard_lord_ds: "Schließe einen Hard-Mode-Run ab.",
      ach_hard_no_death_nm: "Flawless", ach_hard_no_death_ds: "Schließe Hard-Mode ab, ohne zu sterben.",
      ach_challenge_noarmor_nm: "Nacktläufer", ach_challenge_noarmor_ds: "Schließe einen No-Armor-Run ab.",
      ach_challenge_noblaidd_nm: "Einsamer Wolf", ach_challenge_noblaidd_ds: "Schließe einen No-Blaidd-Run ab.",
      ach_challenge_auto_nm: "Zuschauer", ach_challenge_auto_ds: "Schließe einen Auto-Battle-Run ab.",

      // Haligtree Challenge
      node_fortress: "Festung: Besiege den Kommandanten für eine Medaillonhälfte!",
      node_15: "Festung: Besiege den Kommandanten für eine Medaillonhälfte!",
      node_16: "Kanalisation: Etwas Uraltes lauert in der Tiefe der Hauptstadt…",
      node_17: "Etwas glitzert im seichten Wasser…",
      node_18: "Eine vermummte Gestalt wartet am Wegesrand…",
      node_19: "Jump and Run voraus! Der Boden wirkt brüchig…",
      node_20: "Ein uralter Torbogen. Was passiert wohl, wenn man hindurchspringt?",
      tal_desc_katze: "Verringert Fallschaden erheblich. Wirkt im Kampf… nutzlos.",
      tal_langschwanzkatzen_talisman: "Langschwanzkatzen-Talisman",
      fortress_victory_title: "🏰 Festung erobert!",
      fortress_victory_desc: "Du hast den Kommandanten bezwungen und eine Haligtree-Medaillonhälfte erhalten!\n\nMedaillonhälften: {n} / 2",
      haligtree_enter_title: "🌳 Der Haligtree ruft",
      haligtree_enter_desc: "Beide Medaillonhälften vereint! Der geheime Pfad zum Haligtree öffnet sich.\nMalenia wartet am Ende...",
      malenia_phase2_transition: "\n✨ Malenia erhebt sich... Scharlachfäule umhüllt ihren Körper... \n⚔️ Phase 2: Malenia, Göttin der Fäulnis!",
      malenia_victory_title: "🦋 Lord of the Haligtree",
      malenia_victory_desc: "Malenia ist gefallen. Du hast den Haligtree bezwungen und bist nun Lord of the Haligtree!",
      challenge_haligtree: "Haligtree",
      challenge_haligtree_desc: "Finde 2 Festungen, besiege ihre Kommandanten und betritt den geheimen Haligtree. Malenia wartet.",
      ach_challenge_haligtree_nm: "Lord of the Haligtree", ach_challenge_haligtree_ds: "Besiege Malenia im Haligtree-Challenge.",
      weapon_halo_scythe: "Halo Scythe",
      tal_halo_scythe: "Halo Scythe",

      // Run Save & Challenges
      btn_continue: "Run fortsetzen",
      btn_continue_hard: "Hard Run fortsetzen",
      challenge_title: "Challenge Runs",
      challenge_noarmor: "No Armor",
      challenge_noarmor_desc: "Du kannst keine Rüstung anlegen. Nackt durch die Zwischenlande.",
      challenge_noarmor_title: "🛡️ Rüstung abgelehnt",
      challenge_noarmor_decline: "Dein Ehrenkodex verbietet es dir, Rüstung zu tragen. Du lässt sie zurück.",
      challenge_start: "Challenge starten",

      // Hard Mode
      hard_intro_title: "Was dich erwartet:",
      hard_intro_enemies: "Gegner haben +30% mehr HP und Schaden",
      hard_intro_flasks: "1 Flakon weniger pro Klasse, Bosse füllen Flakons nicht auf",
      hard_intro_dodge: "Ausweich-Cap bei 65% statt 75%, Stagger erst nach 5 Treffern",
      hard_intro_talismans: "Nur 2 Talisman-Slots (3. ab Morgott, 4. ab Maliketh)",
      hard_intro_blaidd: "Blaidd braucht 5 Siege und skaliert stärker",
      hard_intro_cursed: "Verfluchte Talismane doppelt so häufig, Fallen härter",
      hard_intro_bossheal: "Kein Waffen-Lager bis zum Feuerriesen",
      hard_intro_btn: "Ich bin bereit. Klassenauswahl ➔",
      class_vagabond_stats_hard: "150 HP · 2 Flakons · 30% Rolle",
      class_samurai_stats_hard: "110 HP · 1 Flakon · 40% Rolle",
      class_wretch_stats_hard: "90 HP · 0 Flakons · 50% Rolle",
      mode_normal_label: "Normal",
      mode_hard_label: "Hard",
      lb_mode_normal: "Normal",
      lb_mode_hard: "Hard",
      lb_cat_normal: "Normal",
      lb_cat_hard: "Hard",
      lb_cat_daily: "🎲 Täglich",
      lb_cat_idle: "⚔️ Gefolge",
      lb_cat_tower: "Battle Tower",
      lb_cat_speedrun: "Speedrun",
      lb_cat_completionist: "100% Club",
      lb_th_time: "Zeit",
      lb_th_date: "Erreicht am",
      lb_th_achievements: "Erfolge",
      lb_th_mode: "Modus",

      talisman_found_title: "Friedhof geplündert!",
      talisman_cursed_title: "Verfluchter Talisman!",
      // Rarity labels
      rarity_common: "Gewöhnlich", rarity_rare: "Selten", rarity_epic: "Episch", rarity_legendary: "Legendär", rarity_cursed: "Verflucht",
      // Talisman names (keys = lowercased, spaces→underscores)
      tal_crimson_amber_medallion: "Crimson Amber Medallion",
      tal_crimson_seed_talisman: "Crimson Seed Talisman",
      tal_axt_talisman: "Axt Talisman",
      tal_schildkröten_talisman: "Schildkröten Talisman",
      tal_radagons_wundensiegel: "Radagons Wundensiegel",
      tal_dungeater_medallion: "Dungeater Medallion",
      tal_havels_medallion: "Havels Medallion",

      // Talisman-Beschreibungen (dynamisch)
      tal_desc_hp: "Erhöht dein maximales Leben um +{v}%.",
      tal_desc_heal: "Verbessert deine Estus-Heilung um +{v}%.",
      tal_desc_dmg: "Erhöht deinen Waffenschaden um +{v}%.",
      tal_desc_dodge: "+{v}% Chance auszuweichen.",
      tal_desc_radagon: "+{dmg}% Schaden und +{dodge}% Ausweichen – aber +{taken}% mehr erlittener Schaden.",
      tal_desc_dungeater: "Verflucht: +{dmg}% Schaden, aber +{taken}% erlittener Schaden.",
      tal_desc_havels: "Verflucht: +{hp}% max. Leben, aber -{dodge}% Ausweichen.",
      weapon_storage: "Waffen-Lager",
      region_catacombs: "Katakomben",
      rune_godrick_tip: "Godricks Rune:\n+25% max. HP, +10 DMG, +15% Ausweichen",
      rune_radahn_tip: "Radahns Rune:\n+50% max. HP, +20 DMG",
      rune_morgott_tip: "Morgotts Rune:\nVerdoppelt dein maximales Leben (x2 HP)",
      rune_rennala_tip: "Rennalas Rune:\n50% Chance auf Wiederbelebung mit 50% HP (einmal pro Run)",
      rune_rykard_tip: "Rykards Rune:\n10% Lebensraub auf eigene Treffer",

      // Float & Combat Extras
      float_dodged: "Ausgewichen!",
      heal_log: "🧪 Flakon getrunken! +{hp} HP.",
      estus_tooltip: "Estus-Flakon",
      combat_weakness: "Schwäche",
      combat_resistance: "Resistenz",
      combat_attack_log: "Du führst {weapon} aus und triffst für {dmg} Schaden!",
      combat_dmg_type: "Schadensart",
      dmg_normal: "Normal", dmg_magie: "Magie", dmg_feuer: "Feuer", dmg_heilig: "Heilig",

      // Gegner- & Bossnamen (DE = Original)
      npc_elite_ritter: "Elite-Ritter",
      npc_böser_vogel: "Böser Vogel",
      npc_leyndell_ritter: "Leyndell Ritter",
      npc_feuermönch: "Feuermönch",
      npc_bestienmensch_of_farum_azula: "Bestienmensch of Farum Azula",
      npc_farum_azula_drache: "Farum Azula Drache",
      npc_königlicher_revenant: "Königlicher Revenant",
      npc_godrick__der_verpflanzte: "Godrick, der Verpflanzte",
      npc_sternengeißel_radahn: "Sternengeißel Radahn",
      npc_morgott__der_omenkönig: "Morgott, der Omenkönig",
      npc_feuerriese: "Feuerriese",
      npc_maliketh__die_schwarze_klinge: "Maliketh, die Schwarze Klinge",
      npc_gideon_ofnir__der_allwissende: "Gideon Ofnir, der Allwissende",
      npc_godfrey__der_erste_eldenlord: "Godfrey, der Erste Eldenlord",
      npc_radagon_von_der_goldenen_ordnung: "Radagon von der Goldenen Ordnung",
      npc_eldenbiest: "Eldenbiest",
      npc_blaidd__der_halbwolf: "Blaidd, der Halbwolf",
      npc_dungeon_skelett: "Dungeon Skelett",
      // Runen-Namen + aktiv/gesperrt-Label
      rune_godrick_name: "Godricks Große Rune",
      rune_radahn_name: "Radahns Große Rune",
      rune_morgott_name: "Morgotts Große Rune",
      rune_rennala_name: "Rennalas Große Rune",
      rune_rykard_name: "Rykards Große Rune",
      rune_active_label: "[AKTIV]",
      rune_locked_label: "(noch nicht erbeutet)",

      // Weapon Names (DE = original)
      weapon_großaxt: "Großaxt", weapon_uchigatana: "Uchigatana", weapon_keule: "Keule",
      weapon_dolch: "Dolch", weapon_kurzschwert: "Kurzschwert", weapon_breitschwert: "Breitschwert",
      weapon_rapier: "Rapier", weapon_claymore: "Claymore", weapon_bluthundreißzahn: "Bluthundreißzahn",
      weapon_maltöter_großbeil: "Maltöter Großbeil", weapon_großsterne: "Großsterne", weapon_rostiger_anker: "Rostiger Anker",
      weapon_blasphemous_blade: "Blasphemous Blade", weapon_malenias_blade: "Malenias Blade",
      weapon_goldene_hellebarde: "Goldene Hellebarde", weapon_marikas_hammer: "Marikas Hammer",
      weapon_mohgwyns_heiliger_speer: "Mohgwyns heiliger Speer", weapon_dunkelmondgroßschwert: "Dunkelmondgroßschwert",

      // Boss-/Combat-Titel & Extra-Popups (v1.3 i18n)
      boss_godrick_title: "👑 Godrick besiegt",
      boss_radahn_title: "🌌 Radahn besiegt",
      boss_morgott_title: "⚔️ Morgott besiegt",
      boss_giant_title: "🔥 Feuerriese besiegt",
      boss_maliketh_title: "🐕 Maliketh besiegt",
      boss_gideon_title: "👁️ Gideon besiegt",
      boss_godfrey_title: "🦁 Godfrey besiegt",
      elden_lord_title: "👑 ELDEN LORD",
      invader_title: "Invasion bezwungen!",
      invader_desc: "Der rote Finstergeist zerfällt.\nDeine Klinge erreicht eine neue Schmiedestufe: +{lvl} (+5 Schaden)!",
      elite_title: "🦏 Feind besiegt!",
      skeleton_title: "💀 Wächter zerfällt",
      blaidd_progress_title: "🐺 Quest fortgesetzt",
      blaidd_progress_desc: "Du hast Blaidd in die Flucht geschlagen...\n\nQuest-Fortschritt: {n} / {z}",
      item_used_title: "✨ Item aktiviert!",
      item_used_desc: "Du hast \"{name}\" benutzt.\nDer Buff gilt ab jetzt für die nächsten 10 Kämpfe!",
      talisman_found_auto: "Du hast einen Talisman gefunden und automatisch angelegt:",
      talisman_found_cursed: "Ein verfluchter Talisman zwingt sich an dich – er wurde automatisch angelegt:",
      talisman_btn_bind: "Anlegen",
      talisman_btn_curse: "Fluch akzeptieren",
      talisman_replace_slot: "Ersetze Slot {i}:",
      talisman_discard_new: "❌ Wegwerfen",
      talisman_inventory_full_title: "Inventar voll!",
      talisman_you_found: "Du hast folgenden Talisman gefunden:",
      talisman_must_equip_choose: "Du musst ihn ausrüsten – wähle, welchen Slot er ersetzt:",
      talisman_choose_replace_or_discard: "Wähle einen Slot zum Ersetzen oder wirf den neuen weg:",
      affinity_blood: "Blut",
      affinity_ice: "Eis",
      affinity_both: "Blut & Eis",
      affinity_none: "Keine",
      affinity_word: "Affinität",
      affinity_burst_log: "\n✨ AFFINITÄTS-BURST! ({aff}) +{dmg} Extra-Schaden!",
      affinity_bonus_5: "jeder 5. Angriff macht +5% zusätzlichen Schaden am Feind.",
      affinity_bonus_7: "jeder 5. Angriff macht +7,5% zusätzlichen Schaden am Feind.",
      affinity_bonus_10: "jeder 5. Angriff macht +10% zusätzlichen Schaden am Feind.",
      ach_unlocked_toast: "Achievement freigeschaltet",
      ach_first_win_nm: "Erster Sieg", ach_first_win_ds: "Gewinne deinen ersten Kampf.",
      ach_win_100_nm: "Kriegsveteran", ach_win_100_ds: "Gewinne 100 Kämpfe.",
      ach_win_500_nm: "Schlachtenmeister", ach_win_500_ds: "Gewinne 500 Kämpfe.",
      ach_win_1000_nm: "Tausendsassa", ach_win_1000_ds: "Gewinne 1000 Kämpfe.",
      ach_boss_1_nm: "Halbgott-Jäger", ach_boss_1_ds: "Besiege deinen ersten Boss.",
      ach_boss_10_nm: "Halbgott-Schlächter", ach_boss_10_ds: "Besiege 10 Bosse.",
      ach_boss_50_nm: "Gott unter Göttern", ach_boss_50_ds: "Besiege 50 Bosse.",
      ach_godrick_nm: "Sturmschleier gemeistert", ach_godrick_ds: "Besiege Godrick.",
      ach_radahn_nm: "Die Sterne fallen", ach_radahn_ds: "Besiege Radahn.",
      ach_morgott_nm: "Omenkönig gefallen", ach_morgott_ds: "Besiege Morgott.",
      ach_firegiant_nm: "Schmiede erloschen", ach_firegiant_ds: "Besiege den Feuerriesen.",
      ach_maliketh_nm: "Schwarze Klinge", ach_maliketh_ds: "Besiege Maliketh.",
      ach_elden_lord_nm: "Elden Lord", ach_elden_lord_ds: "Schließe einen Run ab und werde Elden Lord.",
      ach_first_death_nm: "Du bist gestorben", ach_first_death_ds: "Stirb zum ersten Mal.",
      ach_death_50_nm: "Hartnäckig", ach_death_50_ds: "Stirb 50 Mal und gib nicht auf.",
      ach_dungeon_1_nm: "Gruft-Plünderer", ach_dungeon_1_ds: "Schließe einen Dungeon ab.",
      ach_dungeon_10_nm: "Katakomben-Kenner", ach_dungeon_10_ds: "Schließe 10 Dungeons ab.",
      ach_blaidd_nm: "Blaidds Gefährte", ach_blaidd_ds: "Schließe Blaidds Quest ab.",
      ach_talisman_25_nm: "Talisman-Sammler", ach_talisman_25_ds: "Finde 25 Talismane.",
      ach_weapon_25_nm: "Waffennarr", ach_weapon_25_ds: "Finde 25 Waffen.",
      ach_armor_10_nm: "Gut gerüstet", ach_armor_10_ds: "Finde 10 Rüstungen.",
      ach_flask_500_nm: "Estus-süchtig", ach_flask_500_ds: "Trinke 500 Flakons."
    },
    en: {
      // General UI
      author_tag: "by Hoschi",
      mode_normal: "Normal Mode",
      mode_hard: "Hard Mode (In Development)",
      tab_game: "Play",
      tab_leaderboard: "Leaderboard",
      tab_achievements: "Achievements",

      // Account Bar
      loading: "Loading…",
      unregistered: "Not Logged In",
      unregistered_sub: "Sign in to save your progress & leaderboard score online",
      registered_sub: "Logged In · Progress synced to cloud",
      local_mode: "Local Mode",
      local_mode_sub: "Online features not configured yet (see FIREBASE_SETUP.md)",
      btn_login: "Sign in with Google",
      btn_logout: "Sign Out",
      btn_save: "Save",
      lbl_name: "Name:",
      saved_alert: "Name saved: ",

      // Rules
      rules_title: "The Laws of the Lands Between",
      rule_1: "<strong>Path Selection:</strong> Navigate through branching nodes. Choose wisely to venture deeper.",
      rule_2: "<strong>Weapons & Upgrades:</strong> Discover new armaments. Upgrades transfer automatically when swapping weapons.",
      rule_3: "<strong>Blaidd's Quest:</strong> Defeat Blaidd 4 times to unlock his questline and a massive ultimate reward.",
      rule_4: "<strong>Sites of Grace:</strong> Resting at Graces or defeating major bosses fully restores health and flasks.",
      rule_5: "<strong>Great Runes:</strong> Conquer Demigods to unlock and claim their power at the Divine Towers.",

      // Leaderboard
      lb_loading: "Loading Leaderboard…",
      lb_no_entries_online: "No entries yet – be the first!",
      lb_no_entries_local: "No local runs recorded yet. Finish a run to see your name here!",
      lb_local_hint: "(Local Leaderboard – configure Firebase for cross-device cloud sync.)",
      lb_th_player: "Tarnished",
      lb_th_stage: "Stage",
      lb_th_bosses: "Bosses",
      lb_th_score: "Score",

// Map Nodes
      node_1: "Elite Enemy: More Health!",
      node_2: "Ruin Guardian: Weapon Upgrade!",
      node_3: "Defeat Invader: Increases Smithing Level!",
      node_4: "Site of Grace: Full Health",
      node_5: "Boss Fight! The path to the next area!",
      node_6: "Open Chest: Random Talisman!",
      node_7: "Golden Erdtree: +1 Flask and +10% Estus Efficiency",
      node_8: "Divine Tower: Activate Rune!",
      node_9: "NPC Quest: Meet Blaidd!",
      node_10: "Dungeon Catacombs: Enter a mini-stage full of loot!",
      node_11: "Skeleton: Relatively weak.",
      node_12: "Loot Chest: 30% chance for a buff item!",
      node_13: "Traverse Passage: Watch out for traps!",
      node_14: "Cave: Armor Upgrade!",

      // Classes
      class_title: "Choose your class, Tarnished...",
      class_vagabond: "Vagabond",
      class_vagabond_stats: "150 HP · 3 Flasks · 30% Roll",
      class_vagabond_gear: "Greataxe · Vagabond Knight Set",
      class_samurai: "Samurai",
      class_samurai_stats: "110 HP · 2 Flasks · 40% Roll",
      class_samurai_gear: "Uchigatana · Land of Reeds Set",
      class_wretch: "Wretch",
      class_wretch_stats: "90 HP · 1 Flask · 50% Roll",
      class_wretch_gear: "Club · No Armor",

      // Sidebar & Stats
      backpack: "Inventory",
      backpack_empty: "Empty",
      backpack_buff: "Buff Active!",
      storage_title: "⚔️ Weapon Storage",
      storage_empty: "No weapon stored",
      storage_swap_tip: "Click to equip this weapon (swaps with current)",
      quest_ready: "Blaidd: Ready for Reward!",
      talisman_slots: "Talismans",
      talisman_empty: "Empty Talisman Slot",
      talisman_locked: "Locked – unlocks after defeating Maliketh",
      great_runes: "Great Runes",
      btn_new_run: "🔄 Start New Run",
      btn_main_menu: "🏰 Main Menu",
      btn_twitch: "🎥 Twitch Channel",
      btn_discord: "💬 Discord Server",
      current_area: "Current Area",
      hp_display: "HP",
      dodge_roll: "Roll",

      // Combat Arena
      combat_player: "YOU",
      combat_enemy: "ENEMY",
      combat_staggered: "💥 STAGGERED!",
      btn_attack: "⚔️ Attack",
      btn_heal: "🧪 Heal",
      tip_attack: "Strike with your equipped weapon. The enemy attacks immediately after!",
      tip_heal: "Chug an Estus Flask to close heavy wounds. Care: The enemy will counter during this action!",
      log_start: "You challenge: ",
      log_death: "💀 YOU DIED.",
      screen_death: "YOU DIED",

      // Dungeons & Shrines
      catacombs_title: "🏰 Catacombs Discovered",
      catacombs_desc: "You stand before the heavy stone doors of an ancient dungeon. Entering will transport you to a hazardous sub-map full of monsters, rare loot, and an exclusive trial boss at the depth!",
      catacombs_btn: "Enter Dungeon ➔",
      chest_win: "🎁 Item Salvaged!",
      chest_win_desc: "You open a hidden stone chest and secure an item for your inventory:\n\n<strong>{item}</strong>\n({desc})",
      chest_win_btn: "Stash in Inventory ➔",
      chest_full: "🎒 Bag is Full!",
      chest_full_desc: "You discovered a <strong>{item}</strong>, but your inventory has no free slots left!",
      chest_full_btn: "Leave Behind ➔",
      chest_empty: "📦 Empty Chest",
      chest_empty_desc: "The chest contains nothing but ancient dust and brittle bone fragments. Nothing found!",
      chest_empty_btn: "Move On ➔",
      trap_win: "🏃 Safe Passage",
      trap_win_desc: "Navigating gracefully through the dark, you dodge guillotines and pressure plates, reaching the other side completely unscathed!",
      trap_fail: "🏹 Trap Triggered!",
      trap_fail_desc: "You missed a tripwire! Poison darts shoot straight from the catacomb walls.\n\nYou lose <span style='color:#e74c3c; font-weight:bold;'>{dmg} HP</span>.",
      trap_fail_btn: "Patch up wounds & proceed ➔",
      tower_title: "☤ Divine Tower",
      tower_desc: "Present a reclaimed Great Rune at this holy altar to permanently activate its blessing.",
      tower_leave: "Leave Tower ➔",
      tower_btn: "🏯 Battle Tower",
      tower_guide_title: "🗼 Battle Tower",
      tower_guide_sub: "20 floors. One life. How far can you climb?",
      tower_guide_l1: "<b>20 floors</b>, each a small mini-map of fights ending in a boss — random from the boss pool and tougher every floor.",
      tower_guide_l2: "<b>One life:</b> if you die, the ascent is over — restart from floor 1. Your HP carries between floors.",
      tower_guide_l3: "<b>After every boss</b> Melina grants a permanent blessing (damage, max HP, flask, dodge …). Every 5 floors you also activate a <b>Great Rune</b>.",
      tower_guide_l4: "<b>Curse floors</b> (30%): a curse applies to the <b>whole floor</b> — e.g. tougher enemies, Scarlet Rot or half flasks. Shown at the top.",
      tower_guide_l5: "<b>Floor 20: Baby PCR</b> — defeat him to become Master of the Tower.",
      tower_guide_l6: "The tower is <b>brutal</b>: you need a well-leveled character (Roundtable) and a bit of luck. Your Roundtable upgrades carry in fully.",
      tower_guide_start: "Enter the Tower ⚔️",
      tower_guide_close: "Back",
      dex_title: "Eldendex",

      // Rewards & Boss Transitions
      grace_title: "✨ Grace Restored",
      grace_desc: "You rest at a Site of Grace.\nYour vital essence and flasks have been completely replenished!",
      seed_title: "🌳 Golden Seed Found",
      seed_desc: "You discover a glowing Erdtree sapling.\n\nEffect:\n🧪 +1 Flask Capacity\n🧪 Estus now heals {pct}% of your max health!",
      loot_title: "New Weapon Found!",
      loot_desc: "The Guardian falls and leaves behind a powerful weapon:",
      loot_dmg: "Base Damage:",
      loot_type: "Damage Type:",
      loot_current: "(Currently equipped: {name} – Base {dmg})",
      loot_hint: "Note: Equipping will move your current weapon to storage (if space permits), otherwise it is discarded. Upgrades always apply to all weapons in your run.",
      loot_btn_equip: "Equip",
      loot_btn_store: "Inventory",
      loot_btn_replace: "Replace: {name}",
      loot_btn_trash: "❌ Discard",
      armor_title: "🛡️ Armor Cleansed!",
      armor_desc: "The Mini-Boss falls, leaving behind an armor set:",
      armor_reduction: "Damage Negation:",
      armor_current: "Current: {name}",
      armor_btn_equip: "🛡️ Wear Armor",
      arcane_title: "⚔️ Arcane Empowered!",
      arcane_desc: "You have cleansed the depth of the Catacombs.\nYour weapon channels the altar's energy, gaining:",
      arcane_btn: "Return to the Lands Between ➔",
      quest_title: "🐺 Blaidd's Legacy",
      quest_desc: "You have overcome the Half-Wolf 4 times. Claim your ultimate cosmic reward (Quest resets):",
      quest_opt_hp: "❤️ Ranni's Embrace",
      quest_opt_hp_sub: "Permanently increases your maximum health by +50%.",
      quest_opt_dmg: "⚔️ GOLDEN Reforging",
      quest_opt_dmg_sub: "Ascends your active weapon to Legendary tier and adds +40 base damage.",
      quest_opt_roll: "💨 Wolf Instincts",
      quest_opt_roll_sub: "Sets base dodge roll to 65% (hard cap: 75%).",

      // Boss Defeat Text Blocks
      boss_godrick_win: "Godrick is shattered!\nYou claim his Great Rune.\n\nA new pathway opens into the scarlet-rotted blighted wastes... CAELID!",
      boss_radahn_win: "Starscourge Radahn has been conquered!\nThe stars align, and fate resumes its course.\n\nYour next destination is the golden capital... LEYNDELL!",
      boss_morgott_win: "Morgott dissolves into golden dust!\nYou receive Morgott's Great Rune (Doubles your maximum life force).\n\nThe path leads up into the frozen, dangerous heights... MOUNTAINTOPS OF THE GIANTS!",
      boss_giant_win: "The last Giant collapses into the snow!\n\n🎒 Your weapon storage capacity expanded to 2 slots!\n\nA fracture in space hurls you into the crumbling, timeless sky realm... CRUMBLING FARUM AZULA!",
      boss_maliketh_win: "Maliketh has fallen. Destined Death is unleashed!\n\n💍 You can now equip a 4th Talisman slot!\n\nThe Royal Capital burns. Return to the Capital of Ash!",
      boss_gideon_win: "Sir Gideon Ofnir has been silenced.\n\nThe path to the Elden Throne is clear. Prepare for the final ascent!",
      boss_godfrey_win: "Godfrey has granted you his respect and perished.\n\nA final guiding grace awaits right outside the Erdtree core...",
      boss_beast_win: "GOD SLAIN.\n\nYou have shattered the Golden Order and mended the Ring. You stand as the new Elden Lord! GGG!",
      enemy_elite_win: "The Guardian fades.\nYour maximum health increased by +10% (+{hp} HP)!",
      enemy_skeleton_win: "The skeleton crumbles to dust. The path is clear!",
      btn_continue: "Proceed ➔",

      // Items, Affinities, Armor Names
      item_dumpling: "Raw Meat Dumpling",
      item_dumpling_desc: "Increases max health by +15%.",
      item_neck: "Pickled Turtle Neck",
      item_neck_desc: "Increases flat dodge rate by +15%.",
      item_flesh: "Exalted Flesh",
      item_flesh_desc: "Increases physical weapon damage by +15%.",
      affinity_burst: "Burst",
      no_armor: "No Armor",
      armor_reduction_label: "−{pct}% Damage",
      weapon_damage_label: "{dmg} Damage",
      stagger_alert: "\n💥 Enemy staggered!! They cannot attack this round!",
      stagger_stuck: "\n💥 The enemy remains locked in stagger!",
      roll_success: "\n💨 Roll Success! You completely avoid the oncoming swing!",
      roll_fail: "\n{name} catches you at the end of your roll for {dmg} damage!",
      heal_roll_success: "\n💨 Elegantly rolling under the swing while taking a chug!",
      heal_roll_fail: "\n{name} punishes your chug: {dmg} damage!",
      elden_beast_transition: "Radagon crumbles into golden ash...\n✨ BUT FROM THE DARKNESS EMERGES THE ELDEN BEAST! ✨",

      // Achievements Data
      // New Challenges
      challenge_noblaidd: "No Blaidd",
      challenge_noblaidd_desc: "Blaidd's quest is disabled. No encounters, no rewards.",
      challenge_noblaidd_skip_title: "🐺 Blaidd Ignored",
      challenge_noblaidd_skip_desc: "Your code of honor forbids engaging Blaidd. You move on.",
      challenge_autobattle: "Auto-Battle",
      challenge_autobattle_desc: "No manual control. You attack automatically without healing.",
      no_armor: "No Armor",
      status_heading: "STATUS",

      // Seed system & sharing
      seed_label: "Seed",
      seed_placeholder: "Enter seed…",
      seed_apply: "Apply",
      seed_run_warn: "Seed run: achievements, progress, leaderboards & souls are disabled.",
      seed_badge: "Seed run — doesn't count",
      seed_copied: "Seed link copied!",
      share_result: "Copy result",
      share_copied: "✓ Copied!",
      share_fallen: "Fallen in",
      share_victory: "ELDEN LORD",

      // Hard Mode & Challenge Achievements
      ach_complete_10_nm: "Veteran", ach_complete_10_ds: "Complete 10 runs.",
      ach_complete_25_nm: "Legend", ach_complete_25_ds: "Complete 25 runs.",
      ach_hard_5_nm: "Masochist", ach_hard_5_ds: "Complete Hard Mode 5 times.",
      ach_malenia_nm: "Scarlet Bloom", ach_malenia_ds: "Defeat Malenia.",
      ach_rennala_nm: "Queen of the Full Moon", ach_rennala_ds: "Defeat Rennala, Queen of the Full Moon.",
      ach_rykard_nm: "God-Devourer", ach_rykard_ds: "Defeat Rykard, Lord of Blasphemy.",
      ach_unlock_gelmir_nm: "The Volcano's Path", ach_unlock_gelmir_ds: "Follow a mysterious invitation.",
      ach_mohg_omen_nm: "Omen of the Depths", ach_mohg_omen_ds: "Defeat Mohg, the Omen, in the sewers.",
      ach_fall_death_nm: "Should Have Been a Cat", ach_fall_death_ds: "Fall into the chasm beneath the sewers.",
      ach_mohg_nm: "Miquella's Awakening", ach_mohg_ds: "Defeat Mohg, Lord of Blood, and awaken Miquella.",
      ach_unlock_mohgwyn_nm: "Call of Blood", ach_unlock_mohgwyn_ds: "Uncover another secret of the Lands Between.",
      ach_unlock_hard_nm: "A New Trial", ach_unlock_hard_ds: "Unlock Hard Mode.",
      ach_unlock_malenia_nm: "The Hidden Path", ach_unlock_malenia_ds: "Unlock the Haligtree Path.",
      ach_unlock_tower_nm: "Gate to the Tower", ach_unlock_tower_ds: "Unlock the Battle Tower.",
      ach_unlock_liurnia_nm: "A Hidden Secret", ach_unlock_liurnia_ds: "Uncover one of the Lands Between's secrets.",
      ach_loretta_nm: "Knight Fallen", ach_loretta_ds: "Defeat Loretta.",
      ach_niall_nm: "Commander Down", ach_niall_ds: "Defeat Commander Niall.",
      ach_death_100_nm: "Immortal", ach_death_100_ds: "Die 100 times.",
      ach_win_2500_nm: "God of War", ach_win_2500_ds: "Win 2500 fights.",
      ach_all_bosses_nm: "Twilight of the Gods", ach_all_bosses_ds: "Defeat every demigod at least once.",
      ach_hard_lord_nm: "True Elden Lord", ach_hard_lord_ds: "Complete a Hard Mode run.",
      ach_hard_no_death_nm: "Flawless", ach_hard_no_death_ds: "Complete Hard Mode without dying.",
      ach_challenge_noarmor_nm: "Naked Runner", ach_challenge_noarmor_ds: "Complete a No Armor run.",
      ach_challenge_noblaidd_nm: "Lone Wolf", ach_challenge_noblaidd_ds: "Complete a No Blaidd run.",
      ach_challenge_auto_nm: "Spectator", ach_challenge_auto_ds: "Complete an Auto-Battle run.",

      // Haligtree Challenge
      node_fortress: "Fortress: Defeat the commander for a medallion half!",
      node_15: "Fortress: Defeat the commander for a medallion half!",
      node_16: "Sewers: something ancient lurks beneath the capital…",
      node_17: "Something glitters in the shallow water…",
      node_18: "A hooded figure waits by the wayside…",
      node_19: "Jump and Run ahead! The ground looks brittle…",
      node_20: "An ancient archway. What might happen if you leap through it?",
      tal_desc_katze: "Greatly reduces fall damage. Utterly useless in combat… it seems.",
      tal_langschwanzkatzen_talisman: "Longtail Cat Talisman",
      fortress_victory_title: "🏰 Fortress Conquered!",
      fortress_victory_desc: "You defeated the commander and obtained a Haligtree Medallion half!\n\nMedallion halves: {n} / 2",
      haligtree_enter_title: "🌳 The Haligtree Beckons",
      haligtree_enter_desc: "Both medallion halves united! The secret path to the Haligtree opens.\nMalenia awaits at the end...",
      malenia_phase2_transition: "\n✨ Malenia rises again... Scarlet Rot engulfs her body... \n⚔️ Phase 2: Malenia, Goddess of Rot!",
      malenia_victory_title: "🦋 Lord of the Haligtree",
      malenia_victory_desc: "Malenia has fallen. You conquered the Haligtree and became Lord of the Haligtree!",
      challenge_haligtree: "Haligtree",
      challenge_haligtree_desc: "Find 2 fortresses, defeat their commanders, and enter the secret Haligtree. Malenia awaits.",
      ach_challenge_haligtree_nm: "Lord of the Haligtree", ach_challenge_haligtree_ds: "Defeat Malenia in the Haligtree Challenge.",
      weapon_halo_scythe: "Halo Scythe",
      tal_halo_scythe: "Halo Scythe",

      // Run Save & Challenges
      btn_continue: "Continue Run",
      btn_continue_hard: "Continue Hard Run",
      challenge_title: "Challenge Runs",
      challenge_noarmor: "No Armor",
      challenge_noarmor_desc: "You cannot equip any armor. Traverse the Lands Between unprotected.",
      challenge_noarmor_title: "🛡️ Armor Declined",
      challenge_noarmor_decline: "Your code of honor forbids wearing armor. You leave it behind.",
      challenge_start: "Start Challenge",

      // Hard Mode
      hard_intro_title: "What awaits you:",
      hard_intro_enemies: "Enemies have +30% more HP and damage",
      hard_intro_flasks: "1 fewer flask per class, bosses don't refill flasks",
      hard_intro_dodge: "Dodge cap at 65% instead of 75%, stagger after 5 hits",
      hard_intro_talismans: "Only 2 talisman slots (3rd from Morgott, 4th from Maliketh)",
      hard_intro_blaidd: "Blaidd requires 5 victories and scales harder",
      hard_intro_cursed: "Cursed talismans twice as common, traps deal more damage",
      hard_intro_bossheal: "No weapon storage until Fire Giant",
      hard_intro_btn: "I am ready. Choose class ➔",
      class_vagabond_stats_hard: "150 HP · 2 Flasks · 30% Roll",
      class_samurai_stats_hard: "110 HP · 1 Flask · 40% Roll",
      class_wretch_stats_hard: "90 HP · 0 Flasks · 50% Roll",
      mode_normal_label: "Normal",
      mode_hard_label: "Hard",
      lb_mode_normal: "Normal",
      lb_mode_hard: "Hard",
      lb_cat_normal: "Normal",
      lb_cat_hard: "Hard",
      lb_cat_daily: "🎲 Daily",
      lb_cat_idle: "⚔️ Retinue",
      lb_cat_tower: "Battle Tower",
      lb_cat_speedrun: "Speedrun",
      lb_cat_completionist: "100% Club",
      lb_th_time: "Time",
      lb_th_date: "Reached on",
      lb_th_achievements: "Feats",
      lb_th_mode: "Mode",

      talisman_found_title: "Graveyard Plundered!",
      talisman_cursed_title: "Cursed Talisman!",
      // Rarity labels
      rarity_common: "Common", rarity_rare: "Rare", rarity_epic: "Epic", rarity_legendary: "Legendary", rarity_cursed: "Cursed",
      // Talisman names (official EN Elden Ring names)
      tal_crimson_amber_medallion: "Crimson Amber Medallion",
      tal_crimson_seed_talisman: "Crimson Seed Talisman",
      tal_axt_talisman: "Axe Talisman",
      tal_schildkröten_talisman: "Green Turtle Talisman",
      tal_radagons_wundensiegel: "Radagon's Scarseal",
      tal_dungeater_medallion: "Dung Eater's Medallion",
      tal_havels_medallion: "Havel's Medallion",

      // Talisman Descriptions (dynamic)
      tal_desc_hp: "Increases your maximum health by +{v}%.",
      tal_desc_heal: "Improves your Estus healing by +{v}%.",
      tal_desc_dmg: "Increases your weapon damage by +{v}%.",
      tal_desc_dodge: "+{v}% dodge chance.",
      tal_desc_radagon: "+{dmg}% damage and +{dodge}% dodge – but +{taken}% more damage taken.",
      tal_desc_dungeater: "Cursed: +{dmg}% damage, but +{taken}% damage taken.",
      tal_desc_havels: "Cursed: +{hp}% max. health, but -{dodge}% dodge.",
      weapon_storage: "Weapon Storage",
      region_catacombs: "Catacombs",
      rune_godrick_tip: "Godrick's Rune:\n+25% max HP, +10 DMG, +15% dodge",
      rune_radahn_tip: "Radahn's Rune:\n+50% max HP, +20 DMG",
      rune_morgott_tip: "Morgott's Rune:\nDoubles your maximum health (x2 HP)",
      rune_rennala_tip: "Rennala's Rune:\n50% chance to revive at 50% HP (once per run)",
      rune_rykard_tip: "Rykard's Rune:\n10% lifesteal on your hits",

      // Float & Combat Extras
      float_dodged: "Dodged!",
      heal_log: "🧪 Flask chugged! +{hp} HP.",
      estus_tooltip: "Estus Flask",
      combat_weakness: "Weakness",
      combat_resistance: "Resistance",
      combat_attack_log: "You strike with {weapon} and deal {dmg} damage!",
      combat_dmg_type: "Damage Type",
      dmg_normal: "Physical", dmg_magie: "Magic", dmg_feuer: "Fire", dmg_heilig: "Holy",

      // Enemy & boss names (EN)
      npc_elite_ritter: "Elite Knight",
      npc_böser_vogel: "Giant Crow",
      npc_leyndell_ritter: "Leyndell Knight",
      npc_feuermönch: "Fire Monk",
      npc_bestienmensch_of_farum_azula: "Beastman of Farum Azula",
      npc_farum_azula_drache: "Farum Azula Dragon",
      npc_königlicher_revenant: "Royal Revenant",
      npc_godrick__der_verpflanzte: "Godrick the Grafted",
      npc_sternengeißel_radahn: "Starscourge Radahn",
      npc_morgott__der_omenkönig: "Morgott, the Omen King",
      npc_feuerriese: "Fire Giant",
      npc_maliketh__die_schwarze_klinge: "Maliketh, the Black Blade",
      npc_gideon_ofnir__der_allwissende: "Gideon Ofnir, the All-Knowing",
      npc_godfrey__der_erste_eldenlord: "Godfrey, First Elden Lord",
      npc_radagon_von_der_goldenen_ordnung: "Radagon of the Golden Order",
      npc_eldenbiest: "Elden Beast",
      npc_blaidd__der_halbwolf: "Blaidd the Half-Wolf",
      npc_dungeon_skelett: "Dungeon Skeleton",
      // Rune names + active/locked labels
      rune_godrick_name: "Godrick's Great Rune",
      rune_radahn_name: "Radahn's Great Rune",
      rune_morgott_name: "Morgott's Great Rune",
      rune_rennala_name: "Rennala's Great Rune",
      rune_rykard_name: "Rykard's Great Rune",
      rune_active_label: "[ACTIVE]",
      rune_locked_label: "(not yet claimed)",

      // Weapon Names (official EN Elden Ring names)
      weapon_großaxt: "Greataxe", weapon_uchigatana: "Uchigatana", weapon_keule: "Club",
      weapon_dolch: "Dagger", weapon_kurzschwert: "Short Sword", weapon_breitschwert: "Broadsword",
      weapon_rapier: "Rapier", weapon_claymore: "Claymore", weapon_bluthundreißzahn: "Bloodhound's Fang",
      weapon_maltöter_großbeil: "Crescent Moon Axe", weapon_großsterne: "Great Stars", weapon_rostiger_anker: "Rusty Anchor",
      weapon_blasphemous_blade: "Blasphemous Blade", weapon_malenias_blade: "Hand of Malenia",
      weapon_goldene_hellebarde: "Golden Halberd", weapon_marikas_hammer: "Marika's Hammer",
      weapon_mohgwyns_heiliger_speer: "Mohgwyn's Sacred Spear", weapon_dunkelmondgroßschwert: "Dark Moon Greatsword",

      // Boss/Combat Titles & extra popups (v1.3 i18n)
      boss_godrick_title: "👑 Godrick Defeated",
      boss_radahn_title: "🌌 Radahn Defeated",
      boss_morgott_title: "⚔️ Morgott Defeated",
      boss_giant_title: "🔥 Fire Giant Defeated",
      boss_maliketh_title: "🐕 Maliketh Defeated",
      boss_gideon_title: "👁️ Gideon Defeated",
      boss_godfrey_title: "🦁 Godfrey Defeated",
      elden_lord_title: "👑 ELDEN LORD",
      invader_title: "Invasion Repelled!",
      invader_desc: "The red invader dissolves.\nYour blade reaches a new smithing level: +{lvl} (+5 Damage)!",
      elite_title: "🦏 Foe Defeated!",
      skeleton_title: "💀 Skeleton Crumbles",
      blaidd_progress_title: "🐺 Quest Continued",
      blaidd_progress_desc: "You drove Blaidd back...\n\nQuest progress: {n} / {z}",
      item_used_title: "✨ Item Activated!",
      item_used_desc: "You used \"{name}\".\nThe buff now applies for the next 10 battles!",
      talisman_found_auto: "You found a Talisman and equipped it automatically:",
      talisman_found_cursed: "A cursed Talisman forces itself upon you – it was equipped automatically:",
      talisman_btn_bind: "Equip",
      talisman_btn_curse: "Accept Curse",
      talisman_replace_slot: "Replace Slot {i}:",
      talisman_discard_new: "❌ Discard",
      talisman_inventory_full_title: "Inventory Full!",
      talisman_you_found: "You found the following talisman:",
      talisman_must_equip_choose: "You must equip it — choose which slot it replaces:",
      talisman_choose_replace_or_discard: "Choose a slot to replace, or discard the new one:",
      affinity_blood: "Blood",
      affinity_ice: "Frost",
      affinity_both: "Blood & Frost",
      affinity_none: "None",
      affinity_word: "Affinity",
      affinity_burst_log: "\n✨ AFFINITY BURST! ({aff}) +{dmg} bonus damage!",
      affinity_bonus_5: "every 5th hit deals +5% bonus damage to the enemy.",
      affinity_bonus_7: "every 5th hit deals +7.5% bonus damage to the enemy.",
      affinity_bonus_10: "every 5th hit deals +10% bonus damage to the enemy.",
      ach_unlocked_toast: "Achievement Unlocked",
      ach_first_win_nm: "First Victory", ach_first_win_ds: "Win your first battle.",
      ach_win_100_nm: "Veteran of War", ach_win_100_ds: "Win 100 battles.",
      ach_win_500_nm: "Battlemaster", ach_win_500_ds: "Win 500 battles.",
      ach_win_1000_nm: "The Undefeated", ach_win_1000_ds: "Win 1000 battles.",
      ach_boss_1_nm: "Demigod Hunter", ach_boss_1_ds: "Defeat your first major Boss.",
      ach_boss_10_nm: "Demigod Slayer", ach_boss_10_ds: "Defeat 10 major Bosses.",
      ach_boss_50_nm: "God Among Gods", ach_boss_50_ds: "Defeat 50 major Bosses.",
      ach_godrick_nm: "Put Foolish Dancing To Rest", ach_godrick_ds: "Defeat Godrick the Grafted.",
      ach_radahn_nm: "Starscourge Stallion", ach_radahn_ds: "Defeat Starscourge Radahn.",
      ach_morgott_nm: "Flame of Ambition Extinguished", ach_morgott_ds: "Defeat Morgott, the Omen King.",
      ach_firegiant_nm: "Let It Burn", ach_firegiant_ds: "Defeat the Fire Giant.",
      ach_maliketh_nm: "Destined Death Unleashed", ach_maliketh_ds: "Defeat Maliketh, the Black Blade.",
      ach_elden_lord_nm: "Elden Lord", ach_elden_lord_ds: "Complete a run and claim the Elden Throne.",
      ach_first_death_nm: "You Died", ach_first_death_ds: "Suffer your very first death.",
      ach_death_50_nm: "Stubborn Defiance", ach_death_50_ds: "Die 50 times and never give up.",
      ach_dungeon_1_nm: "Grave Robber", ach_dungeon_1_ds: "Clear your first Catacomb Sub-Dungeon.",
      ach_dungeon_10_nm: "Catacomb Cartographer", ach_dungeon_10_ds: "Clear 10 Catacomb Sub-Dungeons.",
      ach_blaidd_nm: "Shadow's Companion", ach_blaidd_ds: "Complete Blaidd's trial 4 times.",
      ach_talisman_25_nm: "Talisman Hoarder", ach_talisman_25_ds: "Acquire 25 Talismans.",
      ach_weapon_25_nm: "Armaments Master", ach_weapon_25_ds: "Acquire 25 weapons.",
      ach_armor_10_nm: "Well Armored", ach_armor_10_ds: "Acquire 10 armor sets.",
      ach_flask_500_nm: "Flask Addict", ach_flask_500_ds: "Drink 500 flasks across your journeys."
    }
  };

  let currentLang = localStorage.getItem("eldenRogueLang") || "de";

  window.i18n = {
    getLang: function () { return currentLang; },
    setLang: function (lang) {
      if (TRANSLATIONS[lang]) {
        currentLang = lang;
        localStorage.setItem("eldenRogueLang", lang);
        document.dispatchEvent(new Event("languageChanged"));
      }
    },
    t: function (key, placeholders) {
      let dict = TRANSLATIONS[currentLang] || TRANSLATIONS["de"];
      let text = dict[key] || TRANSLATIONS["de"][key] || key;
      if (placeholders) {
        Object.keys(placeholders).forEach(k => {
          text = text.replace(new RegExp(`{${k}}`, 'g'), placeholders[k]);
        });
      }
      return text;
    },
    getRawAchievements: function() {
      // Returns mapped structures for eldenrogue-online.js dynamically injected
      return TRANSLATIONS[currentLang];
    }
  };
})();
